version: '3'

services:
    nginx:
        build: requirements/nginx/
        image: nginx
        container_name: nginx
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
            - SSL_CERTIFICATE=${SSL_CERTIFICATE}
            - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - wp_files:/home
        restart: unless-stopped
        networks:
            - inception
    db:
        build: requirements/mariadb/
        image: mariadb
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/home/mariadb
        restart: unless-stopped
        networks:
            - inception
    wordpress:
        build: requirements/wordpress/
        image: wordpress
        container_name: wordpress
        depends_on:
            - db
        volumes:
            - wp_files:/home/wordpress
        ports:
            - "9000:9000"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_ADMIN=${WORDPRESS_DB_ADMIN}
            - WORDPRESS_DB_ADMIN_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_USER_PASSWORD=${WORDPRESS_DB_USER_PASSWORD}
            - WORDPRESS_PATH=${WORDPRESS_PATH}
        restart: unless-stopped
        networks:
            - inception
volumes:
    wp_files:
        driver: local
        driver_opts:
            type: none
            o: 'bind'
            device: '${PATH_LOGIN}/data/wordpress'
    dbdata:
        driver: local
        driver_opts:
            type: none
            o: 'bind'
            device: '${PATH_LOGIN}/data/db'

networks:
    inception:
        driver: bridge
