DROP DATABASE IF EXISTS test;

CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO $MYSQL_USER@'%';

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$MYSQL_ROOT_PASSWORD');
SET PASSWORD FOR 'user'@'localhost' = PASSWORD('$MYSQL_PASSWORD');
FLUSH PRIVILEGES;
